export * from './system/shared/types';
export * from './system/shared/functions';
export { setupUpdater } from './system/static/electron-api/updater-main';
export { setupShortcuts } from './system/static/electron-api/shortcuts-main';
export type { GlobalShortcutDef, MainAction } from './system/static/electron-api/shortcuts-main';
export { setupDeepLinking, flushDeepLink } from './system/static/electron-api/deep-link-main';
export { setupCSP } from './system/static/electron-api/csp-main';
export { setupMenu } from './system/static/electron-api/menu-main';
export { setupSplash } from './system/static/electron-api/splash-main';
export { loadWindowState, trackWindowState } from './system/static/electron-api/window-state';
export type { WindowBounds } from './system/static/electron-api/window-state';
export { setupTray } from './system/static/electron-api/tray-main';
export { startLocalServer } from './system/static/electron-api/server-main';
export type { TrayMenuItemDef, TrayMenuAction } from './system/static/electron-api/tray-main';
import './system/static/electron-api/system-main';
import './system/static/electron-api/power-monitor-main';
import './system/static/electron-api/power-save-blocker-main';
import './system/static/electron-api/screen-main';
import './system/static/capacitor-api/config-main';
import './system/static/capacitor-api/local-notifications-main';
import './system/static/capacitor-api/action-sheet-main';
import './system/static/capacitor-api/dialog-main';
import './system/static/capacitor-api/app-main';
import './system/static/capacitor-api/browser-main';
import './system/static/capacitor-api/filesystem-main';
import './system/static/capacitor-api/preferences-main';
import './system/static/capacitor-api/toast-main';
import './system/generated/plugins-main-auto';
import './user/plugins-main-user';
